blog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
        # url(r'^$', views.post_list, name='post_list'),
        url(r'^$', views.PostListView.as_view(), name='post_list'),
        url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/'\
                r'(?P<post>[-\w]+)/$',
                views.post_detail,
                name='post_detail'),
        ]

board/urls.py
from django.conf.urls import url

from . import views


app_name = 'board'
urlpatterns = [
        url(r'^$', views.IndexView.as_view(), name='index'),
        url(r'^register/$', views.register, name='register'),
        url(r'^(?P<board_id>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
        ]

myBoard/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^board/', include('board.urls')),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^admin/', admin.site.urls),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset()\
                        .filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
            ('dreaft', 'Drafti'),
            ('published', 'Published'),
            )
    
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, related_name='blog_posts')
    publish = models.DateTimeField(default = timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now = True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    objects = models.Manager() # The default manager.
    published = PublishedManager() # the custom manager.


    class Meta:
        ordering = ('-publish',)

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                args=[self.publish.year,
                        self.publish.strftime('%m'),
                        self.publish.strftime('%d'),
                        self.slug])

    def __str__(self):
        return self.title
    

board/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=100)
    pub_date = models.DateTimeField('date published')


class Tag(models.Model):
    title = models.CharField(max_length=20, null=False)

class Board(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length = 200, default='no title', null=False) 

    contents = models.CharField(max_length = 5000)
    hits = models.PositiveSmallIntegerField(default = 0, null=True)
    tag = models.ManyToManyField(Tag)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView

class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'
    

def post_list(request):
    object_list = Post.published.all()
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    
    return render(request, 
                    'blog/post/list.html',
                    {'page':page,
                    'posts':posts})

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                            status='published',
                            publish__year=year,
                            publish__month=month,
                            publish__day=day)
    return render(request, 
                'blog/post/detail.html',
                {'post':post})

board/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic

from .models import Board

class IndexView(generic.ListView):
    template_name = 'board/index.html'
    context_object_name = 'latest_list'

    def get_queryset(self):
        return Board.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Board
    template_name = 'board/detail.html'


def register(request):
    if request.method == "POST":
        """ form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=false)
            post.author = request.user
            post.pub_date = datetime.datetime.now()
            post.save() """
        return HttpResponseRedirect(reverse('board:detail', args=post.pk))
    else:
        # form = PostForm()
        return render(request, 'board/register.html', {'form': 'form'})

blog/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>

<html>
    <head>
	<title>{% block title %} {% endblock %} </title>
	<link href="{% static 'css/blog.css' %}" rel="stylesheet">
    </head>
    <body>
	<div id="content">
	    {% block content %}
	    {% endblock %}
	</div>
	<div id="sidebar">
	    <h2>My blog</h2>
	    <p> this is my blog. </p>
	</div>
    </body>
</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %} {{ post.title }} {% endblock%}

{% block content %}
<h1> {{ post.title }} </h1>
    <p class="date">
	Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|linebreaks }}
{% endblock %}

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %} My blog {% endblock %}

{% block content %}
    <h1> My Blog </h1>
    {% for post in posts %}
    	<h2>
	    <a href="{{ post.get_absolute_url }}">
		{{ post.title }}
	    </a>
	</h2>
	<p class="date">
	    Published {{ post.publish }} by {{ post.author }}
	</p>
	{{ post.body|truncatewords:30|linebreaks }}
    {% endfor %}
    <!--  {% include "./pagination.html" with page=posts %} -->
    {% include "./pagination.html" with page=page_obj %}
{% endblock%}

blog/templates/blog/post/pagination.html
<div class="pagination">
    <span class="step-links">
	{% if page.has_previous %}
	    <a href = "?page={{page.previous_page_number }}">previous</a>
	{% endif %}
	<span class="current">
	    Page {{ page.number }} of {{page.paginator.num_pages }}.
	</span>
	{% if page.has_next %}
	    <a href="?page={{ page.next_page_number }}"> Next </a>

	{% endif %}
    </span>
</div>

board/templates/board/detail.html
<h1> {{ board.title }} </h1>

<ul>
{{ board.contents }}
</ul>
{{ board.pub_date}}

board/templates/board/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'board/style.css' %}" />
{% if latest_list %}
    <ul>
	{% for board in latest_list %}
	<li><a href="{% url 'board:detail' board.id %}">
	    {{ board.title }} </a></li>
	{% endfor %}
    </ul>

{% else %}
	<p> No Contents </p>
{% endif %}

board/templates/board/register.html
<form action="{% url 'board:register' %}" method="post">
    {% csrf_token %}
   title :  <input type="text" name="title"> 
   <br />

    contents : <input type="textarea" name="contents">
    <br />
    <br />
    <input type="submit" value="submit">

</form>